apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: face-type-recommender
  namespace: face-type-ai
spec:
  ingressClassName: nginx
  rules:
    - host: face-type-ai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: face-type-recommender
                port:
                  number: 7860