name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make install

      - name: Format Code
        run: make format

      - name: Run Tests
        run: make test || echo "⚠️ Tests failed, continuing..."   # optional

      # (future) add this if you have training code
      # - name: Train Model
      #   run: make train

      # - name: Evaluate Model
      #   run: make eval

      - name: Install Hugging Face CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Login to Hugging Face
        run: huggingface-cli login --token ${{ secrets.HF_TOKEN }}

      - name: Deploy to Hugging Face Space
        run: |
          huggingface-cli upload asad2662/face-type-classifier . \
            --repo-type=space \
            --commit-message "Auto-deploy from CI/CD pipeline"
